### PR TITLE
 Fix Makefile to compile on Ubuntu-16.04.

### PR DESCRIPTION
**Pull request by Kiran-r**

### CODE REVIEW

**Comment by Kiran-r** [comment]
Fixes #5.

**Comment by Kiran-r** [comment]
Interesting. `make -j` fails while `make` works on the latest ubuntu. ¯\_(ツ)_/¯

**Comment by kjamsh** [comment]
Thanks for the PR Kiran!

It isn't just `make -j` that fails, `make convert_data` will also fail in a freshly cloned repo. The build breaks because the `convert_data` target does not depend on `bliss`, so there is no guarantee that `libbliss.so` exists, but `LDFLAGS` still contains `-lbliss`. So unless `make bliss` has already been run, the linker will error out.

There are two solutions that spring to mind: one is to make `convert_data` depend on `bliss`, another is to separate the bliss part of `LDFLAGS` into a different variable.

I'd prefer the latter since it keeps dependencies clear. [This](https://github.com/pdclab/peregrine/files/5396828/Makefile.txt) is what I mean (ignore the .txt, Github doesn't allow attaching files without extensions). Would you mind updating your PR with it? I'll accept as soon as the build passes

Thanks again, and enjoy your weekend.

**Comment by kjamsh** [comment]
Awesome! Thanks so much!

**Pull request merged**
